'use client';

import { useEffect, useState } from 'react';
import { Explore, PrototypeExplorer } from './AIExplorer';
import './ai.css';
import { blankOption, criteria, evaluate, initialWorkspace, isWorkspace, ratings, type Option, type Workspace } from '../lib/decision';

const storageKey = 'nexus-workspace-v1';
const steps = ['Problem', 'Evidence & constraints', 'Solutions', 'Evaluation', 'Prototype & decision'];

export default function Home() {
  const [work, setWork] = useState<Workspace>(initialWorkspace);
  const [step, setStep] = useState(0);
  const [loaded, setLoaded] = useState(false);
  const [prototype, setPrototype] = useState(false);
  const [storageError, setStorageError] = useState('');
  useEffect(() => {
    try { const saved = localStorage.getItem(storageKey); if (saved) { const parsed: unknown = JSON.parse(saved); if (isWorkspace(parsed)) setWork(parsed); else setStorageError('Saved work could not be read. Starting a new workspace.'); } }
    catch { setStorageError('Local storage is unavailable. Changes may not persist.'); }
    setLoaded(true);
  }, []);
  useEffect(() => { if (!loaded) return; try { localStorage.setItem(storageKey, JSON.stringify(work)); } catch { setStorageError('Could not save locally. Keep this tab open to retain your work.'); } }, [work, loaded]);
  const update = (field: keyof Workspace, value: string) => setWork(w => ({ ...w, [field]: value }));
  const changeOption = (id: string, patch: Partial<Option>) => setWork(w => ({ ...w, options: w.options.map(o => o.id === id ? { ...o, ...patch } : o) }));
  const selected = work.options.find(o => o.id === work.selectedId);
  const canAdvance = step === 0 ? !!work.problem.trim() : step === 2 ? work.options.filter(o => o.title.trim() && o.mechanism.trim()).length >= 2 : true;
  const next = () => { if (canAdvance) setStep(s => Math.min(steps.length - 1, s + 1)); };
  return <main className="shell">
    <header className="masthead"><span className="brand">NEXUS <span className="brandMark">/</span> WORKSPACE</span><span className="local">Local draft · optional AI</span></header>
    <div className="intro"><p className="eyebrow">A structured way through uncertainty</p><h1>Work through the problem, not around it.</h1><p>Capture what you know, compare approaches, and make a decision you can explain. Optional AI suggestions are proposals, not verified facts.</p></div>
    {storageError && <p role="alert" className="notice">{storageError}</p>}
    <nav aria-label="Problem-solving stages"><ol className="stages">{steps.map((name, index) => <li key={name}><button type="button" className={index === step ? 'active' : ''} aria-current={index === step ? 'step' : undefined} onClick={() => setStep(index)}><small>{String(index + 1).padStart(2, '0')}</small>{name}</button></li>)}</ol></nav>
    <section className="stage" aria-labelledby="stage-title"><p className="eyebrow">Stage {step + 1} / {steps.length}</p><h2 id="stage-title">{steps[step]}</h2>
      {step === 0 && <div className="fields"><Field id="problem" label="What problem are you trying to solve?" value={work.problem} onChange={v => update('problem', v)} required hint="Describe the situation, not a preferred solution."/><Field id="stakeholders" label="Who is affected?" value={work.stakeholders} onChange={v => update('stakeholders', v)}/><Field id="goal" label="What would a better outcome look like?" value={work.goal} onChange={v => update('goal', v)}/></div>}
      {step === 1 && <><p className="support">These are your inputs, not independently verified facts. Separate observations from open questions.</p><div className="fields"><Field id="evidence" label="Evidence you have" badge="USER PROVIDED" value={work.evidence} onChange={v => update('evidence', v)} hint="Add sources or observations you can inspect."/><Field id="constraints" label="Constraints" badge="USER PROVIDED" value={work.constraints} onChange={v => update('constraints', v)}/><Field id="unknowns" label="What remains unknown?" badge="UNVERIFIED" value={work.unknowns} onChange={v => update('unknowns', v)}/></div></>}
      {step === 2 && <><p className="support">Write at least two distinct strategies, or use optional AI exploration. Generated ideas are proposed, not validated recommendations.</p><Explore workspace={work} setWorkspace={setWork}/><div className="options">{work.options.map((o, i) => <article className="option" key={o.id}><div className="optionHead"><h3>Approach {i + 1} <span className="badge">PROPOSED</span></h3>{work.options.length > 2 && <button className="quiet" type="button" onClick={() => setWork(w => ({ ...w, options: w.options.filter(item => item.id !== o.id), selectedId: w.selectedId === o.id ? '' : w.selectedId }))}>Remove</button>}</div><Field id={`title-${o.id}`} label="Strategy" value={o.title} onChange={v => changeOption(o.id, { title: v })} short/><Field id={`mechanism-${o.id}`} label="How would it work?" value={o.mechanism} onChange={v => changeOption(o.id, { mechanism: v })}/></article>)}</div><button className="secondary" type="button" disabled={work.options.length >= 6} onClick={() => setWork(w => ({ ...w, options: [...w.options, blankOption(crypto.randomUUID())] }))}>Add another approach</button></>}
      {step === 3 && <><p className="support">Rate each approach yourself. “Strong” is favorable, including for risk (lower risk). Unknowns stay visible; no automatic ranking is implied.</p><div className="options">{work.options.filter(o => o.title.trim()).map(o => <article className="option" key={o.id}><h3>{o.title} <span className="badge">PROPOSED</span></h3><p>{o.mechanism || 'Mechanism not described.'}</p><div className="ratings">{criteria.map(c => <label key={c} htmlFor={`${c}-${o.id}`}>{c}<select id={`${c}-${o.id}`} value={o.ratings[c]} onChange={e => changeOption(o.id, { ratings: { ...o.ratings, [c]: e.target.value as typeof ratings[number] } })}>{ratings.map(r => <option key={r} value={r}>{r}</option>)}</select></label>)}</div><p className="assessment">{evaluate(o)}</p></article>)}</div>{!work.options.some(o => o.title.trim()) && <p>No approaches yet. Return to Solutions to add them.</p>}</>}
      {step === 4 && <><p className="support">Select a direction and test its core interaction. The walkthrough and optional AI outline are not deployed products.</p><label className="selectLabel" htmlFor="direction">Selected direction</label><select id="direction" value={work.selectedId} onChange={e => { update('selectedId', e.target.value); setPrototype(false); }}><option value="">Choose an approach</option>{work.options.filter(o => o.title.trim()).map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select>{selected && <div className="prototype"><p className="eyebrow">INTERACTIVE WALKTHROUGH · PROPOSED</p><h3>{selected.title}</h3><p>{selected.mechanism}</p><button type="button" className="primary" onClick={() => setPrototype(p => !p)}>{prototype ? 'Reset walkthrough' : 'Try this direction'}</button>{prototype && <div role="status" className="result"><strong>Walkthrough outcome</strong><p>Imagine applying this mechanism to: {work.problem || 'the problem you described'}</p><p>Check the constraints: {work.constraints || 'none recorded yet'}. Unresolved: {work.unknowns || 'none recorded yet'}.</p><p>This illustrates a decision path; it does not validate feasibility or impact.</p></div>}</div>}{selected && <PrototypeExplorer key={selected.id} workspace={work}/>}<Field id="reason" label="Why choose this direction?" value={work.decisionReason} onChange={v => update('decisionReason', v)} hint="Refer to evidence, trade-offs and remaining uncertainties."/><div className="trail"><h3>Decision trail</h3><dl><dt>Problem</dt><dd>{work.problem || 'Not entered'}</dd><dt>Evidence</dt><dd>{work.evidence || 'Not supplied'} <span className="badge">USER PROVIDED</span></dd><dt>Constraints</dt><dd>{work.constraints || 'Not supplied'}</dd><dt>Selected approach</dt><dd>{selected?.title || 'Not selected'}</dd><dt>Reason</dt><dd>{work.decisionReason || 'Not recorded'}</dd><dt>Still unknown</dt><dd>{work.unknowns || 'Not recorded'} <span className="badge">UNVERIFIED</span></dd></dl></div></>}
      <div className="actions"><button className="secondary" type="button" disabled={step === 0} onClick={() => setStep(s => s - 1)}>Back</button>{step < steps.length - 1 && <button className="primary" type="button" disabled={!canAdvance} onClick={next}>Continue <span aria-hidden="true">→</span></button>}</div>{!canAdvance && <p className="support" role="status">{step === 0 ? 'Describe the problem to continue.' : 'Add two approaches with a name and mechanism to continue.'}</p>}
    </section><footer>Drafts remain in this browser. Optional AI requests send your input to your configured provider. Clear site data to remove the local draft.</footer>
  </main>;
}
function Field({ id, label, value, onChange, hint, badge, short, required }: { id: string; label: string; value: string; onChange: (value: string) => void; hint?: string; badge?: string; short?: boolean; required?: boolean }) {
  return <div className="field"><label htmlFor={id}>{label} {badge && <span className="badge">{badge}</span>}</label>{short ? <input id={id} value={value} onChange={e => onChange(e.target.value)} required={required} maxLength={160}/> : <textarea id={id} value={value} onChange={e => onChange(e.target.value)} required={required} rows={3} maxLength={3000} aria-describedby={hint ? `${id}-hint` : undefined}/>} {hint && <p id={`${id}-hint`} className="hint">{hint}</p>}</div>;
}
